### ISSUE TITLE
long dimension for collar pieces is wrong in PDF

### ISSUE THREAD

**Issue by snicker** [abroekhof/waldbasketbag#1]
cooked one of these up in the past week as my first sewing project, thank you for doing all the work of measuring and writing out the process!!

I have not checked the DXF, but the long dimension for the 2x collar pieces seems off. I modified to 2'-0 1/4" and still had a slight bit of slack (This is with 1/8" foam and a 3/8" seam allowance)

The basket section should have a closed perimeter dimension of  `(1'-2" * 2) + ( 9" * 2 ) = 3'-10" (46")` when finished with a 3/8" seam allowance.

However, the current dimensions for the collars read `2'-2.75"`, which results in a "tube" perimeter dimension of `4'-4" (52")` with a 3/8" seam. This leaves 6 inches of slack in the tube that must be folded in.

As a novice and not knowing how much slack I needed to provide, I modified the collar long dimension to `2'-0 1/4"` resulting in a closed tube perimeter of 47". Even this additional inch had to be folded in around the corners, and I believe I could've used less material.

completed bag attached! I love it!
![image](https://user-images.githubusercontent.com/221540/106492559-ea97e200-646c-11eb-9c67-178bb41b644b.png)

**Comment by limnoted** [comment]
I’m currently finishing up a bag using this pattern and I noticed the same thing re. the collar pieces being too long.
I calculated that each piece could be 60.4 cm long including seam allowances.
However, I’d be hesitant to recommend that people cut it that short, given small individual differences between bags.
What I did was cut the pieces to the recommended length, then pinned the pieces to the bottom of the bag & marked where the appropriate overlap would occur.
Then I unpinned the upper & trimmed to the appropriate length.
On the one hand my approach wastes two ~10 cm strips of fabric (relatively expensive x-pac in my case), but on the other hand it avoids cutting the pieces too short & wasting big pieces of fabric.

When I’m done my bag I’ll post some suggested edits to the instructions, re. the approach described above & recommended collar piece dimensions. Overall it has been a really fun experience and is my first sewing project! The basket portion fits like a glove into the 137. I’ve made a couple of other small changes like adding interior sleeve pockets on the sides, and d-rings in the corners for a shoulder belt. I’ve also made a metric version of your CAD drawings. I’ll post all of these together to Git. I really wanted to make a zippered pass through into the main bag at the base, but sadly it’s beyond my skill for now 😊

Ted

**Comment by abroekhof** [comment]
Hey all, apologies for not responding earlier—apparently I don't get email notifications for GitHub, and haven't checked here for a while. Let me take a look at what you've all found and I'll get back to you.

Thanks!

**Comment by abroekhof** [comment]
Fixed in 165dba0fb4bb8f1230684b154ff010319ab40a85

I'm not sure what happened here, but I've updated the collar width to be 23", plus 3/8" on either side for seam allowance. This should produce a 46" collar, as you calculated above @snicker. 

By the way, bag looks great, where did you get that fabric?

**Comment by snicker** [comment]
@abroekhof https://www.spoonflower.com/ is where I found it- seems to be a cool site where anyone can upload a pattern and they will print to a fabric of your choice. not exactly cheap, but the options are endless. This was a denim fabric in and out, I was considering waxing it for protection, but I'm seeing how my stitching holds up with commuter rides around town. Thanks again for the pattern!!
