### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by aocole** [abroekhof/waldbasketbag#2]
This isn't a real issue, it's just my way of saying thanks for this pattern. I messed around with the straps and maybe made some bad choices, but we'll see!

![IMG_4868 Large](https://user-images.githubusercontent.com/393591/168453509-03933b36-a459-4510-887c-3ec6a82c8b41.jpeg)
![IMG_4867 Large](https://user-images.githubusercontent.com/393591/168453510-11729bc6-da2d-4772-a376-66a3e8e1fea4.jpeg)
![IMG_4865 Large](https://user-images.githubusercontent.com/393591/168453511-91d028d7-c6ba-4b47-81ad-920036ddf01e.jpeg)
![IMG_4864 Large](https://user-images.githubusercontent.com/393591/168453512-e7d0e718-411a-4c3a-bee5-1fe787f80bdc.jpeg)

Good job on the pattern and thanks for sharing it!

**Comment by aocole** [comment]
No action required

**Comment by abroekhof** [comment]
@aocole nice work, looks awesome! That LED strip is pretty cool too.

Yeah, I've been thinking about alternative strap configs, since it does get a bit tiresome always having to thread the long straps through the rack. I think other brands use velcro to secure it, which might be interesting.
